config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :medications, only: [:index, :show, :edit, :update, :destroy, :create, :new]
  resources :intakes, only: [:index, :update]
  get "calendar", to: "intakes#calendar"
  get "home", to: "pages#home"
  get "month-calendar", to: "intakes#month_calendar"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/intake.rb
class Intake < ApplicationRecord
  belongs_to :medication
  validates :expected_intake, presence: true

  scope :morning, ->(date) { where(expected_intake: DateTime.new(date.year, date.month, date.day, 0)..DateTime.new(date.year, date.month, date.day, 12)).order(:expected_intake) }
  scope :afternoon, ->(date) { where(expected_intake: DateTime.new(date.year, date.month, date.day, 12)..DateTime.new(date.year, date.month, date.day, 17)).order(:expected_intake) }
  scope :evening, ->(date) { where(expected_intake: DateTime.new(date.year, date.month, date.day, 17)..DateTime.new(date.year, date.month, date.day, 24)).order(:expected_intake) }

  def overdue?
    DateTime.now > expected_intake && !complete
  end
end

app/models/medication.rb
class Medication < ApplicationRecord
  attr_accessor :intake_times, :interval

  # after_create :generate_intakes
  belongs_to :user
  has_many :intakes, dependent: :destroy

  # private

  def generate_intakes(interval, intake_times)
    # interval => ["Monday", "Tuesday", "Thursday", "Saturday"]
    # intake_times => ["7:00am", "1:00pm", "7:00pm"]
    start_date = self.start_date # Fri, 02 Dec 2022
    end_date = self.end_date # end_date user input inside klammern # Mon, 05 Dec 2022
    date = start_date # Fri, 02 Dec 2022
    while date <= end_date
      if interval.include?(Date::DAYNAMES[date.wday])
        intake_times.each do |intake_time|
          # intake_time => "7:00am" "7:00pm"
          if intake_time[-2..] == "12:00pm"
            hour = 12
          elsif intake_time[-2..] == "am"
            hour = intake_time.split(":")[0].to_i
          else
            hour = intake_time.split(":")[0].to_i + 12
          end
          intake_time_of_day = DateTime.new(date.year, date.month, date.day, hour)
          Intake.create(expected_intake: intake_time_of_day, medication: self)
        end
      end
      date += 1.day
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :medications, dependent: :destroy
  has_many :intakes, through: :medications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/intakes_controller.rb
class IntakesController < ApplicationController
  def index
    # There is a date in params
    if params[:date]
      numbers = params[:date].split("-").map(&:to_i)
      chosen_date = Date.new(numbers[0], numbers[1], numbers[2])
    end

    @selected_date = (chosen_date || Date.today)

    @morning_intakes = current_user.intakes.morning(@selected_date)
    @afternoon_intakes = current_user.intakes.afternoon(@selected_date)
    @evening_intakes = current_user.intakes.evening(@selected_date)
  end

  def month_calendar
    @intakes = Intake.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
    )
  end


  def update
    @completed_intake = Intake.find(params[:id])
    @completed_intake.toggle!(:complete)
    @completed_intake.save
    respond_to do |format|
      format.html { redirect_to intakes_path }
      format.text { render partial: "intakes/intake_card", locals: {intake: @completed_intake}, formats: [:html] }
    end
  end

end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  def index
    @medications = current_user.medications
  end

  def show
    @medication = Medication.find(params[:id])
  end

  def edit
    @medication = Medication.find(params[:id])
  end

  def update
    @medicatin = Medication.find(params[:id])
    @medication.update(medication_params)
    redirect_to medication_path(@medication)
  end

  def destroy
    @medication = Medication.find(params[:id])
    @medication.destroy
    redirect_to medications_path, status: :see_other
  end

  def new
    @medication = Medication.new
  end

  def create
    @medication = Medication.new(medication_params)
    @medication.user = current_user
    if @medication.save
      @medication.generate_intakes(params[:medication][:interval], params[:medication][:intake_times])
      redirect_to medication_path(@medication), notice: "Medication sucessfully created!"

    else
      render :new
    end
  end

  private

  def medication_params
    params.require(:medication).permit(:name, :start_date, :end_date, :dose, :comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @next_intake = Intake.all.order(:expected_intake).where(expected_intake: DateTime.now..).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/intakes/_intake_card.html.erb
<div class="intake-card <%= intake.complete ? "active" : "" %> <%= intake.overdue? ? "red" : "" %>"
    data-controller="update-complete"
    data-action="click->complete#taken">
  <%= link_to intake_path(intake), data: { turbo_method: "PATCH", action: "click->update-complete#swapCard" }, class: "tick-off-circle" do %>
    <i class="fa-solid fa-check"></i>
  <% end %>

  <h4>
    <%= link_to "#{intake.medication.name}", medication_path(intake.medication) %>
    <%= "(overdue)" if intake.overdue? %>
  </h4>

  <p>Dose: <%= intake.medication.dose %></p>
  <p><%= intake.expected_intake.strftime("at %I:%M%p") %></p>
</div>

app/views/intakes/_month_calendar.html.erb
<div class="container">
<%#= calendar(start_date: Date.today.at_beginning_of_week, number_of_days: 7) do |date| %>
  <%# if date == Date.today %>
    <!-- <p><strong><%#= date.day %></strong></p> -->
  <%# else %>
    <!--  <p><%#= date.day %></p> -->
  <%# end %>
<%# end %>
<!-- </div> -->

<% beginning_of_current_week = Date.today.at_beginning_of_week %>
<% four_weeks = (beginning_of_current_week - 2.weeks..beginning_of_current_week + 2.weeks).to_a %>

<div class="days-container" data-controller="horizontal-scroll">

  <% four_weeks.each_with_index do |date, index| %>
    <% if date == @selected_date %>
      <%= link_to intakes_path(date: date.strftime("%Y-%m-%d")), class: "day-card", data: { horizontal_scroll_target: "selectedDate", index: index } do %>
        <span id="today" class="day-number"><%= date.day %></span>
        <span id="weekday"><%= date.strftime("%a")  %></span>
      <% end %>

    <% else %>
      <%= link_to intakes_path(date: date.strftime("%Y-%m-%d")), class: "day-card", data: { horizontal_scroll_target: "day", index: index } do %>
        <span class="day-number"><%= date.day %></span>
        <span id="weekday"><%= date.strftime("%a")  %></span>
      <% end %>
    <% end %>

  <% end %>

</div>

app/views/intakes/index.html.erb
<div class="Your-Intakes-Calendar-Index">

  <div class="intakes-h1">
    <h1>Your Intakes</h1>
  </div>

  <div class="calendar">
    <%= render "month_calendar" %>
  </div>

  <%# <div class="link-all-medications-intakes">
    <%= link_to "See All Medications", medications_path %>
  <%# </div> %>

  <div class="Tabs-container">

    <div class="Tabs">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Morning</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Daytime</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Evening</button>
        </li>
      </ul>
    </div>


    <div class="tab-content" id="pills-tabContent">

      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <% if @morning_intakes.present? %>
          <div class="Intakes-Index">
            <% @morning_intakes.each do |intake| %>
              <%= render "intake_card", intake: intake %>
            <% end %>
          </div>
        <% else %>
          <h6 id="no-med-card"> No Medications to take!</h6>
        <% end %>
      </div>




      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <% if @afternoon_intakes.present? %>
          <div class="Intakes-Index">
            <% @afternoon_intakes.each do |intake| %>
              <%= render "intake_card", intake: intake %>
            <% end %>
          </div>
        <% else %>
          <h6 id="no-med-card"> No Medications to take!</h6>
        <% end %>
      </div>

      <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
        <% if @afternoon_intakes.present? %>
          <div class="Intakes-Index">
          <% @evening_intakes.each do |intake| %>
            <%= render "intake_card", intake: intake %>
          <% end %>
          </div>
        <% else %>
          <h6 id="no-med-card"> No Medications to take!</h6>
        <% end %>
      </div>

    </div>

  </div>

</div>

app/views/intakes/intake.html.erb
<h1>all my intakes</h1>

<%= @intake %>

app/views/intakes/month_calendar.html.erb
<div class="container">
<%#= calendar(start_date: Date.today.at_beginning_of_week, number_of_days: 7) do |date| %>
  <%# if date == Date.today %>
    <!-- <p><strong><%#= date.day %></strong></p> -->
  <%# else %>
    <!--  <p><%#= date.day %></p> -->
  <%# end %>
<%# end %>
<!-- </div> -->

<% beginning_of_current_week = Date.today.at_beginning_of_week %>
<% four_weeks = (beginning_of_current_week - 2.weeks..beginning_of_current_week + 2.weeks).to_a %>

<div class="days-container" data-controller="horizontal-scroll">
  <% four_weeks.each do |date| %>
    <% if date == Date.today %>
      <div class="day-card" data-horizontal-scroll-target="day">
        <span id="today" class="day-number"><%= date.day %></span>
        <span id="weekday"><%= date.strftime("%a")  %></span>
      </div>
    <% else %>
    <div class="day-card">
      <span class="day-number"><%= date.day %></span>
      <span id="weekday"><%= date.strftime("%a")  %></span>
    </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pocket Nurse Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <title>Pocket Nurse Application</title>
<meta name="Pocket nurse Application" content="Pocket Nurse Application">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="Pocket Nurse" />
<meta property="og:type" content="website" />
<meta property="og:url" content="www.pocketnurse.online" />
<meta property="og:image" content="Asset 2.png" />
<meta property="og:description" content="Health app reminder" />
<meta property="og:site_name" content="<%= meta_title %>" />


  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/medications/edit.html.erb
<%= simple_form_for(medication) do |f| %>
  <%= f.input :name %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :dose %>
  <%= f.input :intake_times %>
  <%= f.input :interval %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/medications/index.html.erb
<div class="all-medications">
  <%= link_to "Back", :back %>
  
  <div id="all-medications-title">
    <h1> All Medications</h1>
  </div>

  <div class="cards-container">
    <% @medications.each do |medication| %>
      <div class="medication-index-card">
        <h2><%= link_to "#{medication.name.upcase}", medication_path(medication) %></h2>
        <p><strong>Dose:</strong> <%= medication.dose %></p>
        <p><strong>From</strong>  <%= medication.start_date %> <strong>To</strong> <%= medication.end_date %></p>

        <div class="d-flex justify-content-end" data-controller="sweet-alert" data-sweet-alert-medication-name-value="<%= medication.name %>">
          <%= link_to "", medication_path(medication), data: { turbo_method: :delete, sweet_alert_target: "link" }, class: "hidden" %>
          <button data-action="click->sweet-alert#popUp" class="trash-can">
            <%= image_tag "trash.png" %>
          </button>
        </div>

      </div>
    <% end %>

    <div class="btn-add-medication">
      <a><%= link_to "Add Medication", new_medication_path %></a>
    </div>

  </div>

</div>

app/views/medications/new.html.erb
<div class="add-medication-container">
  <div class="add-medication-card">
    <%= link_to "Back", :back %>
    <div class="card-content">
      <div class="image-title">
        <h1>Add Medication</h1>
        <%= image_tag "pills.svg" %>
      </div>
        <%= simple_form_for(@medication) do |f| %>
          <%= f.input :name %>
          <%= f.input :dose %>
          <%= f.input :start_date %>
          <%= f.input :end_date%>
          <%= f.input :intake_times, label: 'Time',
                      as: :select,
                      collection: ["12:00am"] + (1..11).map {|h| "#{h}:00am"}.to_a + ["12:00pm"] + (1..11).map {|h| "#{h}:00pm"}.to_a,
                      input_html: { multiple: true, class: "time-selector" },
                      include_hidden: false %>
          <%= f.input :interval, label: 'Weekdays',
                      as: :select,
                      collection: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
                      input_html: { multiple: true, class: "interval-selector" },
                      include_hidden: false %>
          <%= f.input :comment %>
          <%= f.submit class: "btn-save-medication" %>
        <% end %>
    </div>
  </div>
</div>

app/views/medications/show.html.erb
<div class="show-individual-medication">

    <div class="show-content">
      <%= link_to "Back", :back %>

      <div class="show-iage-doc">
        <%= image_tag "undraw_scientist_re_6v28.svg" %>
      </div>

      <h1><%= @medication.name.upcase %></h1>

      <h5>DURATION:</h5>
      <p><%= @medication.start_date %> - <%= @medication.end_date %></p>

      <h5>DOSE:</h5>
      <p><%= @medication.dose %></p>

      <div class="comment-box">
        <p>Comments:</p>
        <p><%= @medication.comment %></p>
      </div>

      <div class="btn-add-medication">
        <a><%= link_to "Add Medication", new_medication_path %></a>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <% if user_signed_in? %>
    <h2 class="home-title" >Hello!</h2>

    <div class="home-container">

      <div class="image-doctors-heart">
        <%= image_tag ("doctors-heart.svg") %>
      </div>


      <div class="medications">
        <h3><%= link_to "Medications", intakes_path %></h3>
        <% unless @next_intake.blank? %>
          <h5>YOUR NEXT MED. INTAKE:</h5>
          <p><strong><%= @next_intake.medication.name %></strong></p>
          <p><strong><%= @next_intake.medication.dose%></strong></p>
          <p><strong><%= @next_intake.expected_intake.strftime("%m/%d/%Y, at %I:%M%p") %></strong></p>
        <% else %>
          <p>You have no medications to take.</p>
        <% end %>
      </div>

      <div class="appointments">
        <h3>Appointments</h3>
        <h5>YOUR NEXT DOCTOR'S APPOINTMENT:</h5>
        <p><strong>Dr.med. Prager</strong></p>
        <p><strong>Dentist Checkup</strong></p>
        <p><strong>15/01/2023, at 15:45PM</strong></p>
      </div>

    <% else %>
      <div class="landing-page-container">

        <div class="image-doctors-heart-landing">
          <%= image_tag ("doctors-heart.svg") %>
        </div>

        <div class="lading-page-header" >
          <h2>Welcome to</h2>
          <h2 class="pn">Pocket Nurse!</h2>
        </div>

        <p class="lading-page-text">We are here to help you stay on track with your medication prescriptions & health appointments!</p>

        <h5 class="lading-page-btn"><%= link_to "Sign Up", new_user_registration_path %></h5>

      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <div class="pocket-nurse-text-logo">
      <%= link_to "Pocket Nurse", home_path %>
    </div>

    <% if user_signed_in? %>
      <div class="nav-item dropdown">
        <%= image_tag "menu.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end custom-navbar-menu" aria-labelledby="navbarDropdown" style="position: absolute; right: -20px;">
          <div class="links-container">
            <h5>Hello,</h5>
            <h5>Here is your Menu</h5>
            <%= link_to "Home", home_path, class: "dropdown-item" %>
            <%= link_to "Your Intakes", intakes_path, class: "dropdown-item" %>
            <%= link_to "All Medications", medications_path, class: "dropdown-item" %>
            <%= link_to "Add Medication", new_medication_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </div>
    <% end %>
  </div>
</div>